### ISSUE TITLE
请求支持配置文件，方便批量替换

### ISSUE THREAD

**Issue by photkey** [sillsun/FileIconMOD#1]
使用配置文件在换新机的时候 只要运行一次就可以了，比较方便，而且经常在安装一些软件的时候会覆盖之前设置的图标/默认应用,这个时候也只要直接再运行一次就可以了。

**Comment by sillsun** [comment]
配置文件批量修改我可以加一下，这些代码我都忘差不多了，我记得这程序的机制好像是需要有这些默认图标的文件才能修改，要解决你这个问题，最难的我感觉是要有默认图标文件。

**Comment by sillsun** [comment]
v3.0的release已经上传，支持配置批量修改。
